services:
  - type: web
    name: nail-detection-api
    env: python
    buildCommand: pip install -r requirements_backend.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9